volumes:
  rabbitmq_data:
    external:
        name: ${RABBITMQ_VOLUME_NAME:-rabbitmq_data}
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
